config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
 resources :pictures do
   collection do
     post :confirm
   end
 end
 resources :users, only: [:new, :show, :edit, :create, :update]
 resources :sessions, only: [:new, :create, :destroy]
 resources :favorites, only: [:create, :destroy, :index]

 # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :image, presence: true
  validates :content, presence: true
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :face, FaceUploader

  validates :password, presence: true, length: { minimum: 6 }
  validates :face, presence: true
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  before_validation { email.downcase! }

  has_secure_password
  has_many :pictures
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end

  def index
    @user = current_user
    @favorites = Favorite.where(user_id: @user.id).all
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    else
      if @picture.save
        # PictureMailer.contribution_mail(@picture).deliver
        redirect_to pictures_path, notice: "作成しました"
      else
        render :new
      end
    end
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "更新しました"
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice:"削除しました"
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  private
  def picture_params
    params.require(:picture).permit(:content, :image, :image_cache)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
    def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id), notice: 'アカウントを作成しました'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: '更新しました'
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :face, :face_cache)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/favorites/index.html.erb
<h2>お気に入り一覧</h2>
<% @favorites.each do |favorite| %>
<ul>
  <li><%= image_tag(favorite.picture.image.url) if favorite.picture.image && favorite.picture.image.url %></li>
  <li>ユーザー: <%= favorite.picture.user.name %></li>
  <li>内容: <%= favorite.picture.content %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="breadcrumb">
      <% if logged_in? %>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><%= link_to "Profile", user_path(current_user.id) %></li>
        <li class="breadcrumb-item"><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
        <li class="breadcrumb-item"><%= link_to '新しく投稿する', new_picture_path %></li>
        <li class="breadcrumb-item"><%= link_to 'お気に入り一覧', favorites_path %></li>
        <% else %>
        <li class="breadcrumb-item"><%= link_to "Sign up", new_user_path %></li>
        <li class="breadcrumb-item"><%= link_to "Login", new_session_path %></li>
      </ol>
        <% end %>
    </nav>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true, url: choose_new_or_edit) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>
  <div class="blog_title">
    <%= form.label :image %><br>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <div class="blog_title">
    <%= form.label :content %><br>
    <%= form.text_field :content, class:"form-control" %>
  </div>
    <%= form.submit class:"btn btn-secondary form_b new_b" %>
<% end %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @picture,  url: pictures_path, local: true ) do |form| %>
  <p>image:<br><%= image_tag(@picture.image.url)if @picture.image && @picture.image.url %></p>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <p>本文:<br><%= @picture.content %></p>
  <%= form.submit  "登録する", class:"btn btn-secondary new_b" %>
  <%= form.submit "戻る", name: 'back', class:"btn btn-secondary new_b" %>
<% end %>

app/views/pictures/edit.html.erb
<h2>編集する</h2>
  <%= render 'form' %>

app/views/pictures/index.html.erb
<h1>一覧</h1>
<% @pictures.each do |picture| %>
  <ul class="index_list">
    <li><%= image_tag picture.image.url %></li>
    <li>ユーザー: <%= picture.user.name %></li>
    <li>内容: <%= picture.content %></li>
    <%= link_to '詳細', picture_path(picture.id), class:"btn btn-secondary" %>
      <% if logged_in? %>
      <% if picture.user.id == current_user.id %>
      <%= link_to ' 編集', edit_picture_path(picture.id), data: { confirm: '本当に編集していいですか？' }, class:"btn btn-secondary"  %>
      <%= link_to ' 削除', picture_path(picture.id), method: :delete, data: { confirm: '本当に削除していいですか？' }, class:"btn btn-secondary"  %>
      <% end %>
      <% end %>
  </ul>
<% end %>

app/views/pictures/new.html.erb
<h2>作成する</h2>
  <%= render 'form' %>

app/views/pictures/show.html.erb
<div class="card" style="width: 506px;>
  <div class="bd-placeholder-img card-img-top">
    <p>image: <%= image_tag @picture.image.url %></p>
  </div>
  <div class="card-body">
    <p>内容: <%= @picture.content %></p>
  </div>
<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-secondary' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-secondary' %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザー編集</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
<ul>
  <li>
    <%= f.label :profile_image %>
    <%= f.file_field :face %>
  </li>
  <li>
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
  </li>
  <li>
    <%= f.label :email %>
    <%= f.email_field :email, class:"form-control" %>
  </li>
  <li>
    <%= f.label :password %>
    <%= f.password_field :password, class:"form-control" %>
  </li>
  <li>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class:"form-control" %>
  </li>
</ul>
  <%= f.submit "Update my account",class: "btn btn-secondary" %>
<% end %>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
<ul>
  <li>
    <%= f.label :profile_image %>
    <%= f.file_field :face %>
  </li>
  <li>
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
  </li>
  <li>
    <%= f.label :email %>
    <%= f.email_field :email, class:"form-control" %>
  </li>
  <li>
    <%= f.label :password %>
    <%= f.password_field :password, class:"form-control" %>
  </li>
  <li>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class:"form-control" %>
  </li>
</ul>
  <%= f.submit "Create my account",class: "btn btn-secondary" %>
<% end %>

app/views/users/show.html.erb
<div class="card" style="width: 306px;">
  <div class="bd-placeholder-img card-img-top">
    <p class="card-text">プロフィール画像: </p>
    <%= image_tag @user.face.url %>
  </div>
  <div class="card-body">
    <p class="card-text">ユーザー名: <%= @user.name %></p>
    <p class="card-text">メールアドレス: <%= @user.email %></p>
  </div>
</div>

<% if logged_in? %>
  <% if @user.id == current_user.id %>
    <%= link_to "編集する", edit_user_path(@user), class:"btn btn-secondary" %>
    <%= link_to "新規投稿する", new_picture_path, class:"btn btn-outline-secondary" %>
    <%= link_to "投稿一覧へ", pictures_path, class:"btn btn-outline-secondary" %>
  <% end %>
<% end %>